"use client";
import { useState } from "react";
import type { DashboardData } from "./lib/supabase";

const tabs=["Visão geral","Computadores","Ocorrências","Inventário","Atualizações","Retenção"];
const eventLabels:Record<string,string>={ProhibitedApplicationDetected:"Aplicativo proibido detectado",SessionLocked:"Sessão bloqueada",SessionUnlocked:"Sessão desbloqueada",SessionStarted:"Login registrado"};
const eventName=(type:string)=>eventLabels[type]??type;
const ago=(iso:string)=>{const m=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));return m<1?"agora":m<60?`há ${m} min`:`há ${Math.round(m/60)} h`};

export function Dashboard({initialData,operatorName}:{initialData:DashboardData;operatorName:string}){
 const [tab,setTab]=useState("Visão geral"); const [selected,setSelected]=useState<string[]>([]); const [message,setMessage]=useState(""); const [query,setQuery]=useState(""); const [device,setDevice]=useState(""); const [retention,setRetention]=useState(initialData.retentionDays);
 const online=initialData.devices.filter(d=>Date.now()-new Date(d.last_seen_at).getTime()<5*60000).length;
 const alerts=initialData.events.filter(e=>e.event_type==="ProhibitedApplicationDetected").length;
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const schedule=async(type:string,releaseId?:string)=>{setMessage("Enviando tarefa...");try{const r=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,deviceIds:selected,releaseId})});if(!r.ok)throw new Error();setMessage("Tarefa criada. As máquinas executarão quando sincronizarem.");}catch{setMessage("Conecte o Supabase e publique o painel privado para criar tarefas.");}};
 const saveRetention=async()=>{setMessage("Salvando política...");try{const r=await fetch("/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({retentionDays:retention})});if(!r.ok)throw new Error();setMessage("Política salva. A limpeza automática será executada diariamente.");}catch{setMessage("Conecte o Supabase para salvar a política de retenção.");}};
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark">LM</div><div><strong>LabMonitor</strong><span>IFMS • Administração</span></div></div><nav className="nav">{tabs.map((t,i)=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><span className="navIcon">{["⌂","▣","!","◫","↻","⌛"][i]}</span><span className="navLabel">{t}</span></button>)}</nav><div className="sideFoot"><span className="onlineDot"/>Servidor operacional<br/><small>Sincronização a cada 5 min</small></div></aside><main className="main"><header className="topbar"><div className="crumb">Laboratórios / <b>{tab}</b></div><div className="operator"><strong>{operatorName}</strong><span>Operador autorizado</span></div></header><div className="content"><div className="heading"><div><h1>{tab}</h1><p>Monitoramento e administração das estações Windows.</p></div><span className="live">● Atualização automática</span></div>
 {!initialData.configured&&<div className="notice">Modo de demonstração: o painel está pronto, mas precisa das credenciais do Supabase para exibir máquinas reais.</div>}
 {tab==="Visão geral"&&<><div className="grid4"><Metric label="Computadores" value={initialData.devices.length} note="cadastrados" icon="▣"/><Metric label="Online agora" value={online} note={`${initialData.devices.length-online} sem comunicação`} icon="●" green/><Metric label="Ocorrências recentes" value={alerts} note="exigem revisão" icon="!" warning/><Metric label="Softwares catalogados" value={initialData.softwareTotal} note="instalações encontradas" icon="◫"/></div><div className="twoCol"><DeviceTable data={initialData} selected={selected} toggle={toggle}/><EventPanel data={initialData}/></div></>}
 {tab==="Computadores"&&<div className="panel sectionPanel"><div className="panelHead"><h2>Estações cadastradas</h2><button className="btn primary" disabled={!selected.length} onClick={()=>schedule("inventory_refresh")}>Atualizar inventário</button></div><DeviceRows data={initialData} selected={selected} toggle={toggle}/>{message&&<div className="notice">{message}</div>}</div>}
 {tab==="Ocorrências"&&<div className="panel sectionPanel"><div className="panelHead"><h2>Registro de eventos</h2><span>{initialData.events.length} eventos recentes</span></div><EventRows data={initialData}/></div>}
 {tab==="Inventário"&&<div className="panel sectionPanel"><div className="panelHead"><h2>Inventário consolidado</h2><span>{initialData.softwareTotal} instalações</span></div><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar software ou fabricante"/><select value={device} onChange={e=>setDevice(e.target.value)}><option value="">Todos os computadores</option>{initialData.devices.map(d=><option value={d.id} key={d.id}>{d.hostname}</option>)}</select></div><SoftwareRows data={initialData} query={query} device={device}/></div>}
 {tab==="Atualizações"&&<><div className="panel sectionPanel"><div className="panelHead"><h2>Atualização do agente</h2><span>Pacotes assinados e verificados</span></div><DeviceRows data={initialData} selected={selected} toggle={toggle}/><div className="actionRow"><select className="btn"><option>Selecione uma versão</option>{initialData.releases.filter(r=>r.active).map(r=><option key={r.id}>Versão {r.version}</option>)}</select><button className="btn primary" disabled={!selected.length||!initialData.releases.length} onClick={()=>schedule("agent_update",initialData.releases.find(r=>r.active)?.id)}>Enviar atualização</button></div>{message&&<div className="notice">{message}</div>}</div><div className="panel sectionPanel"><div className="panelHead"><h2>Histórico de tarefas</h2><span>{initialData.jobs.length} recentes</span></div><JobRows data={initialData}/></div></>}
 {tab==="Retenção"&&<div className="panel sectionPanel"><div className="panelHead"><h2>Limpeza automática dos eventos</h2><span>executada diariamente às 03:15 UTC</span></div><div className="retentionBox"><div><b>Manter ocorrências por</b><p>Somente os eventos são excluídos. Máquinas, inventário, versões e tarefas permanecem.</p></div><select className="btn" value={retention} onChange={e=>setRetention(Number(e.target.value))}><option value={30}>30 dias</option><option value={60}>60 dias</option><option value={90}>90 dias</option><option value={180}>180 dias</option><option value={365}>1 ano</option></select><button className="btn primary" onClick={saveRetention}>Salvar política</button></div>{message&&<div className="notice">{message}</div>}</div>}
 </div></main></div>;
}
function Metric({label,value,note,icon,green,warning}:{label:string;value:number;note:string;icon:string;green?:boolean;warning?:boolean}){return <div className="metric"><div className="metricTop"><span>{label}</span><span className="metricIcon">{icon}</span></div><b>{value}</b><small className={green?"up":warning?"warn":""}>{note}</small></div>}
function DeviceTable({data,selected,toggle}:{data:DashboardData;selected:string[];toggle:(id:string)=>void}){return <div className="panel"><div className="panelHead"><h2>Estado das estações</h2><span>última comunicação</span></div><DeviceRows data={data} selected={selected} toggle={toggle}/></div>}
function DeviceRows({data,selected,toggle}:{data:DashboardData;selected:string[];toggle:(id:string)=>void}){return <div className="tableWrap"><table><thead><tr><th></th><th>Computador</th><th>Estado</th><th>Agente</th><th>Softwares</th><th>Último contato</th></tr></thead><tbody>{data.devices.map(d=>{const on=Date.now()-new Date(d.last_seen_at).getTime()<5*60000;return <tr key={d.id}><td><input aria-label={`Selecionar ${d.hostname}`} type="checkbox" checked={selected.includes(d.id)} onChange={()=>toggle(d.id)}/></td><td><div className="machine"><span className="machineIcon">▣</span><b>{d.hostname}</b></div></td><td><span className="status"><i className={`dot ${on?"on":""}`}/>{on?"Online":"Offline"}</span></td><td><span className="badge">v{d.agent_version}</span></td><td>{d.software_count??0}</td><td>{ago(d.last_seen_at)}</td></tr>})}</tbody></table></div>}
function EventPanel({data}:{data:DashboardData}){return <div className="panel"><div className="panelHead"><h2>Atividade recente</h2><span>tempo real</span></div><div className="eventList">{data.events.slice(0,5).map(e=><div className="event" key={e.event_id}><i className="eventPin"/><div className="eventText"><b>{eventName(e.event_type)}</b><span>{e.devices?.hostname} • {e.user_name??"SYSTEM"}</span></div><time>{ago(e.occurred_at)}</time></div>)}</div></div>}
function EventRows({data}:{data:DashboardData}){return <div className="tableWrap"><table><thead><tr><th>Horário</th><th>Evento</th><th>Computador</th><th>Usuário</th><th>Detalhe</th></tr></thead><tbody>{data.events.map(e=><tr key={e.event_id}><td>{new Date(e.occurred_at).toLocaleString("pt-BR")}</td><td><span className={`badge ${e.event_type==="ProhibitedApplicationDetected"?"high":""}`}>{eventName(e.event_type)}</span></td><td>{e.devices?.hostname}</td><td>{e.user_name??"SYSTEM"}</td><td>{String(e.payload?.displayName??"—")}</td></tr>)}</tbody></table></div>}
function SoftwareRows({data,query,device}:{data:DashboardData;query:string;device:string}){const q=query.toLowerCase();const rows=data.software.filter(s=>(!device||s.device_id===device)&&(!q||s.name.toLowerCase().includes(q)||(s.publisher??"").toLowerCase().includes(q)));return <div className="tableWrap"><table><thead><tr><th>Software</th><th>Versão</th><th>Fabricante</th><th>Computador</th><th>Escopo</th><th>Arquitetura</th></tr></thead><tbody>{rows.map(s=><tr key={`${s.device_id}-${s.inventory_key}`}><td><b>{s.name}</b></td><td>{s.version||"—"}</td><td>{s.publisher||"—"}</td><td>{s.devices?.hostname}</td><td>{s.scope}</td><td>{s.architecture}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Nenhum software encontrado.</div>}</div>}
function JobRows({data}:{data:DashboardData}){return <div className="tableWrap"><table><thead><tr><th>Computador</th><th>Tarefa</th><th>Estado</th><th>Início</th><th>Resultado</th></tr></thead><tbody>{data.jobs.map((j,i)=><tr key={i}><td>{j.devices?.hostname}</td><td>{j.jobs?.type==="agent_update"?"Atualizar agente":"Atualizar inventário"}</td><td><span className="badge">{j.status}</span></td><td>{j.leased_at?new Date(j.leased_at).toLocaleString("pt-BR"):"Aguardando"}</td><td>{String(j.result?.message??"—")}</td></tr>)}</tbody></table>{!data.jobs.length&&<div className="empty">Nenhuma tarefa enviada.</div>}</div>}
